apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-logs-volume
  labels:
    app: nginx
    volume: logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/log/
